main/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import login_view, logout_view, Profile

app_name = "accounts"

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', Profile.as_view(), name='profile'),

]

main/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/webapp/urls.py
from django.urls import path

from webapp.views import AnnounceListView, AnnounceCreateView, AnnounceUpdateView, AnnounceDetailView, AnnounceNewList, \
    AnnounceModUpdate, AnnounceDeleteView

app_name = "webapp"

urlpatterns = [
    path('', AnnounceListView.as_view(), name="announce_list"),
    path('announce/create/', AnnounceCreateView.as_view(), name="announce_create"),
    path('announce/update/<int:pk>/', AnnounceUpdateView.as_view(), name="announce_update"),
    path('announce/detail/<int:pk>/', AnnounceDetailView.as_view(), name="announce_detail"),
    path('announce/moder/list/', AnnounceNewList.as_view(), name="announce_moder_list"),
    path('announce/moder/<int:pk>/update/', AnnounceModUpdate.as_view(),
         name="announce_moder_update"),
    path('announce/delete/<int:pk>/', AnnounceDeleteView.as_view(), name="announce_delete"),
]

main/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class Client(AbstractUser):
    phone = models.CharField(max_length=24)

main/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.urls import reverse_lazy

User = get_user_model()

ANNOUNCE_STATUS = (
    ("new", "новая"),
    ("published", 'опубликовано'),
    ("reject", "отклонено"),
)


class Announce(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="announces")
    photo = models.ImageField()
    title = models.CharField(max_length=128)
    text = models.TextField(max_length=2024)
    price = models.IntegerField(null=True, blank=True)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateField(auto_now_add=True)
    published_at = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=48, choices=ANNOUNCE_STATUS, default="new")

    def __str__(self):
        return f"{self.title} : {self.status}"

    def get_absolute_url(self):
        return reverse_lazy("webapp:announce_list")

main/webapp/forms.py
from django import forms

from webapp.models import Announce


class AnnounceForm(forms.ModelForm):
    class Meta:
        model = Announce
        exclude = ["status", "published_at", "author"]


class AnnounceModerForm(forms.ModelForm):
    class Meta:
        model = Announce
        fields = ["status"]


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

main/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.views.generic import DetailView

from accounts.models import Client

User = get_user_model()

# Create your views here.


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username, password=password)
        except ObjectDoesNotExist:
            user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:announce_list')
        else:
            context['has_error'] = True
    return render(request, 'accounts/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:announce_list')


class Profile(DetailView):
    model = Client
    template_name = "accounts/profile.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data()
        print(context)
        print(context.get('client'))
        print(context.values())
        return context

main/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from webapp.forms import AnnounceForm, AnnounceModerForm
from webapp.models import Announce


class AnnounceListView(ListView):
    model = Announce
    paginate_by = 3
    template_name = "announce/announce_list.html"
    context_object_name = 'announces'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status__exact="published")
        return queryset


class AnnounceCreateView(LoginRequiredMixin ,CreateView):
    model = Announce
    form_class = AnnounceForm
    template_name = "announce/announce_create.html"
    success_url = reverse_lazy("webapp:announce_list")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class AnnounceUpdateView(PermissionRequiredMixin, UpdateView):
    model = Announce
    form_class = AnnounceForm
    template_name = "announce/announce_update.html"
    success_url = reverse_lazy("webapp:announce_list")

    def has_permission(self):
        return self.request.user == self.get_object().author


class AnnounceDetailView(DetailView):
    model = Announce
    template_name = 'announce/announce_detail.html'


class AnnounceDeleteView(PermissionRequiredMixin, DeleteView):
    model = Announce
    success_url = reverse_lazy("webapp:announce_list")
    template_name = "announce/announce_delete.html"

    def has_permission(self):
        return self.request.user == self.get_object().author


class AnnounceNewList(PermissionRequiredMixin, ListView):
    model = Announce
    context_object_name = 'announces'
    template_name = 'announce/moder_list.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status__exact='new').order_by("-created_at")
        return queryset

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_announce')


class AnnounceModUpdate(PermissionRequiredMixin, UpdateView):
    model = Announce
    template_name = "announce/moder_update.html"
    form_class = AnnounceModerForm

    def has_permission(self):
        return self.request.user.has_perm('webapp.change_announce')

main/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
{% endblock content %}

main/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ client.username }}</h1>
    <div>{{ client.phone}}</div>

    <div class="row">
{% for announce in client.announces.all %}
<div class="card" style="width: 18rem;">
  <img src="{{ announce.photo.url }}" class="card-img-top" alt="{{ announce.photo.url }}">
  <div class="card-body">
    <h5 class="card-title">{{ announce.title }}</h5>
    <p class="card-text">{{ announce.text }}</p>
    <a href="{% url 'webapp:announce_detail' announce.pk %}" class="btn btn-primary">Открыть</a>
  </div>
</div>
    {% endfor %}
</div>


{% endblock content %}

main/templates/announce/announce_create.html
{% extends 'base.html' %}
{% block content%}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' %}
    </form>

{% endblock content %}

main/templates/announce/announce_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="post">
    <h1>Вы уверены что хотите удалить {{ announce.title }} ?</h1>
    <button type="submit">Да</button>
    </form>
    <a href="{% url 'webapp:announce_detail' announce.pk %}"><button>Нет</button></a>

{% endblock content %}

main/templates/announce/announce_detail.html
{% extends 'base.html' %}
{%  block content %}

    <img src="{{ announce.photo.url }}" alt="">
    <div>{{ announce.author }}</div>
    <div>{{ announce.title }}</div>
    <div>{{ announce.created_at }}</div>
    <div>{{ announce.price }}</div>
    <div>{{ announce.updated_at }}</div>
    <div>{{ announce.status }}</div>
        {% if user is announce.author %}
    <div><a href="{% url "webapp:announce_update" announce.pk %}">
        <button>Изменить</button>
    </a></div>
            <a href="{% url "webapp:announce_delete" announce.pk %}"><button>Удалить</button></a>
        {% endif %}


    {% if perms.webapp.change_announce %}
    <p>
        <div><a href="{% url "webapp:announce_moder_update" announce.pk %}">
        <button>Изменить статус</button>
        </a></div>
        <a href="#"><button>Опублиовать</button></a>
        <a href="#"><button>Отклонить</button></a>
    </p>
    {% endif %}
{% endblock content %}

main/templates/announce/announce_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
{% for announce in announces.all %}
<div class="card" style="width: 18rem;">
  <img src="{{ announce.photo.url }}" class="card-img-top" alt="{{ announce.photo.url }}">
  <div class="card-body">
    <h5 class="card-title">{{ announce.title }}</h5>
    <p class="card-text">{{ announce.text }}</p>
    <a href="{% url 'webapp:announce_detail' announce.pk %}" class="btn btn-primary">Открыть</a>
  </div>
</div>
    {% endfor %}
</div>

{% endblock %}

main/templates/announce/announce_update.html
{% extends 'base.html' %}
{% block content%}

    {% include 'partial/announce_update.html' %}

{% endblock content %}

main/templates/announce/moder_list.html
{% extends 'base.html' %}

{% block content %}

    {% include 'partial/annouce_list.html' %}

{% endblock %}

main/templates/announce/moder_update.html
{% extends 'base.html' %}

{% block content %}

    {% include 'partial/announce_update.html' %}

{% endblock %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Document{% endblock title %}</title>
</head>
<body class="container">
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webapp:announce_list' %}">Все</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:announce_create' %}">Создать</a>
        </li>
          {% if perms.webapp.change_announce %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'webapp:announce_moder_list' %}">Модерация</a>
        </li>
          {% endif %}
      {% endif %}
      </ul>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}"><button>Выйти</button></a>
        </li>
            {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}"><button>Войти</button></a>
        </li>{% endif %}
        </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

main/templates/partial/annouce_list.html
<div class="row">
{% for announce in announces.all %}
<div class="card" style="width: 18rem;">
  <img src="{{ announce.photo.url }}" class="card-img-top" alt="{{ announce.photo.url }}">
  <div class="card-body">
    <h5 class="card-title">{{ announce.title }}</h5>
    <p class="card-text">{{ announce.text }}</p>
    <a href="{% url 'webapp:announce_detail' announce.pk %}" class="btn btn-primary">Открыть</a>
  </div>
</div>
    {% endfor %}
</div>
{% if is_paginated %}
   {% include 'partial/pagination.html' %}
{% endif %}

main/templates/partial/announce_update.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'partial/form.html' with button_text="Изменить" %}
</form>

main/templates/partial/form.html
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {{ field }}
{% endfor %}

<br>
{% if not fields_only %}
    <input class="btn btn-primary mt-3" type="submit" value={{ button_text|default:"Сохранить" }}>
{% endif %}

main/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>